models:
    bracken:
        staging: bracken/stg_bracken.sql
        clean: bracken/clean.sql

    fastqs:
        staging: fastqs/stg_fastqs.sql
        clean:
            default: fastqs/pp_fastqs_pe.sql
            20241105_AV234501_B-PE75-Ad-HiO: fastqs/pp_fastqs_pe.sql
            230119_B001_Lib: fastqs/pp_fastqs_pe.sql
            230913_B002_B001_Lib: fastqs/pp_fastqs_pe.sql
            240704_B002_B001_Lib_AVITI_reseq: fastqs/pp_fastqs_pe.sql

    # Manual caching to assist smk/nxf
    identification_cache:
        create_db: pipeline_caching/identification/create.sql
        insert_db: pipeline_caching/identification/insert.sql

    # Manual caching to assist smk/nxf
    mapping_cache:
        create_db: pipeline_caching/mapping/create.sql
        insert_db: pipeline_caching/mapping/insert.sql

    nfcore_inputs:
        bactmap: nfcore_inputs/bactmap.sql
        sarek: nfcore_inputs/sarek.sql
        taxprofiler: nfcore_inputs/taxprofiler.sql

    reference_genomes:
        create_db: reference_genomes/create.sql
        prepare_insert: reference_genomes/update_progress.sql
        update_db: reference_genomes/insert.sql
    
    sample_info:
        clean:
            default: samples/clean.sql
            20241105_AV234501_B-PE75-Ad-HiO: "samples/20241105_AV234501_B-PE75-Ad-HiO.sql"
            230119_B001_Lib: samples/230119_B001_Lib.sql
            230913_B002_B001_Lib: samples/230913_B002_B001_Lib.sql
            240704_B002_B001_Lib_AVITI_reseq: samples/230913_B002_B001_Lib.sql

    samplesheet:
        create_db: samplesheet/create.sql
        prepare_insert: samplesheet/clean.sql
        update_db: samplesheet/insert.sql
    
    sequencing_info:
        clean:
            default: sequencing/230913_B002_B001_Lib.sql
            20241105_AV234501_B-PE75-Ad-HiO: "sequencing/20241105_AV234501_B-PE75-Ad-HiO.sql"
            230119_B001_Lib: sequencing/230119_B001_Lib.sql
            230913_B002_B001_Lib: sequencing/230913_B002_B001_Lib.sql
            240704_B002_B001_Lib_AVITI_reseq: sequencing/230913_B002_B001_Lib.sql

    variants:
        create_db: variants/create.sql
        insert_db: variants/insert.sql

    vcfs:
        clean:
            default: vcfs/clean_bactmap.sql
            legacy_mapping: vcfs/clean_legacy_mapping.sql
            sarek_bcftools: vcfs/clean_sarek_bcftools.sql
            sarek_deepvariant: vcfs/clean_sarek_deepvariant.sql
            sarek_freebayes: vcfs/clean_sarek_freebayes.sql
            sarek_haplotypecaller: vcfs/clean_sarek_haplotypecaller.sql
            snippy: vcfs/clean_snippy.sql

seeds:
    types:
        contigs: contigs_type.csv
        idtools: idtools_type.csv
        maptools: maptools_type.csv
        relationship: relationship_type.csv
        reference_genomes: reference_genome_type.csv
        species: species_type.csv
        timepoint: timepoint_type.csv